Repository lblod/app-gelinkt-notuleren, pull requests merged in 2021-09, with the labels that each got.

#43 bump frontend
  docker-compose.yml
Labels: internal

#44 bump frontend
  docker-compose.yml
Labels: internal

#45 Add versioned behandeling relationship to behandeling
  config/resources/slave-besluit-domain.lisp
Labels: internal

#46 correctly update agenda title
  docker-compose.yml
Labels: bug

#47 Remove requirebranch config from release-it.json
  .release-it.json
Labels: internal

#48 bump frontend 2.13.0 -> 2.14.0
  docker-compose.yml
Labels: enhancement

#49 bump prepublisher
  docker-compose.yml
Labels: enhancement

#50 bump prepublishler
  docker-compose.yml
Labels: bug

#52 Internal/bump prepublisher
  docker-compose.yml
Labels: internal

#53 bump frontend and prepublisher
  docker-compose.yml
Labels: internal

#54 bump frontend and prepbulisher
  docker-compose.yml
Labels: internal
