Repository lblod/app-gelinkt-notuleren, pull requests merged in 2021-08, with the labels that each got.

#38 Bump frontend and prepublisher
  docker-compose.yml
Labels: internal

#41 Enhancement/async signing and publication of notulen
  CHANGELOG.md
  docker-compose.yml
Labels: enhancement

#42 bump published-resource-producer
  CHANGELOG.md
  docker-compose.yml
Labels: bug
