Repository lblod/app-gelinkt-notuleren, pull requests merged in 2022-02, with the labels that each got.

#71 Annotate new KB
  config/migrations/20220202165308-annotate-kb-19751201-algemeen-reglement.sparql
Labels: enhancement

#72 bump frontend
  docker-compose.yml
Labels: bug

#73 bump frontend
  docker-compose.yml
Labels: bug

#75 Fix some typos in AR template
  config/migrations/20220209230112-fix-typos-legal-context.sparql
Labels: enhancement

#76 Bump editor from 2.20.4 to 2.20.5
  docker-compose.yml
Labels: enhancement

#78 Fix the title of the besluit mobilitiet template
  config/migrations/20220214113000-fix-title-mobility-template-againsparql
Labels: bug

#80 bump frontend from 2.20.6 to 2.21.0
  docker-compose.yml
Labels: internal
