Repository lblod/app-gelinkt-notuleren, pull requests merged in 2022-11, with the labels that each got.

#118 Add inverse agendapoint relation to stemming
  config/resources/slave-besluit-domain.lisp
Labels: enhancement

#121 chore(deps): bump frontend to v2.31.5
  docker-compose.yml
Labels: internal, hotfix

#123 Add include-uri to document-container model
  config/resources/master-editor.lisp
Labels: enhancement

#124 Update frontend to 2.34.0
  docker-compose.yml
Labels: internal

#119 Feature: linking documents as parts of other documents.
  config/resources/master-editor.lisp
Labels: enhancement

#128 Add migration which replaces bepaald by bepaalt in besluit nieuwe stijl
  config/migrations/20221117145046-fix-typos-besluit-nieuwe-stijl.sparql
Labels: bug

#129 Bump prepublish service to 1.7.0
  docker-compose.yml
Labels: internal

#130 Bump frontend to 2.35.0
  docker-compose.yml
Labels: internal
