Repository lblod/app-gelinkt-notuleren, pull requests merged in 2022-12, with the labels that each got.

#131 :cloud: Upgrade frontend to 2.36.0
  docker-compose.yml
Labels: internal

#132 :cloud: Upgrade editor to 2.36.1
  docker-compose.yml
Labels: internal

#135 hotfix: bump editor to v2.36.2
  docker-compose.yml
Labels: bug, hotfix

#134 bump migrations service
  docker-compose.yml
Labels: internal

#133 Fix wrong cased relationshipt on regulatory statement
  config/resources/slave-publicatie-gn-domain.lisp
Labels: bug
