Repository lblod/app-gelinkt-notuleren, pull requests merged in 2023-04, with the labels that each got.

#151 Add migration which fixes the typos of the mobiliteit template
  config/migrations/20230414125136-fix-mobiliteit-template-typos.sparql
Labels: bug

#150 Add support for deleting signatures and publishing logs
  config/authorization/config.ex
  config/dispatcher/dispatcher.ex
  config/resources/master-editor.lisp
  config/resources/slave-publicatie-gn-domain.lisp
Labels: enhancement

#152 update frontend to 3.4.0
  docker-compose.yml
Labels: internal

#153 Update frontend to 3.4.1
  docker-compose.yml
Labels: internal
