Repository lblod/app-gelinkt-notuleren, pull requests merged in 2023-06, with the labels that each got.

#161 support deletion of signatures
  config/dispatcher/dispatcher.ex
  config/resources/domain.lisp
  docker-compose.yml
Labels: enhancement, breaking

#162 chore(deps)!: bump prepublisher to v2.0.0
  docker-compose.yml
Labels: breaking

#163 GN-4355: Show signage of "reader" role in publication actions
  CHANGELOG.md
  config/authorization/config.ex
Labels: bug

#164 chore: bump frontend to 5.1.0
  docker-compose.yml
Labels: internal
