Repository lblod/app-gelinkt-notuleren, pull requests merged in 2024-10, with the labels that each got.

#199 Add only article attr to templates
  .changeset/slimy-mayflies-tan.md
  config/migrations/20241021143900-update-templates-to-detect-only-article.sparql
Labels: bug

#201 GN-5094: addition of migrations for the next legislation
  .changeset/angry-wombats-dress.md
  .changeset/beige-emus-vanish.md
  .changeset/five-bobcats-run.md
  .changeset/six-queens-relax.md
  .changeset/wild-cups-brush.md
  config/authorization/config.ex
  config/dispatcher/dispatcher.ex
  config/migrations/2024/2024-09/20240906104711-delete-versioned-notulen.sparql
  config/migrations/2024/2024-10/20241022085311-districten/20241022085311-districten.graph
  config/migrations/2024/2024-10/20241022085311-districten/20241022085311-districten.ttl
  config/migrations/2024/2024-10/20241022085311-districten/20241022085312-district-borsbeek.graph
  config/migrations/2024/2024-10/20241022085311-districten/20241022085312-district-borsbeek.ttl
  config/migrations/2024/2024-10/20241022085311-districten/20241022085313-districten-mock-users.sparql
  config/migrations/2024/2024-10/20241022085314-fusiegemeenten-2025/20241022085314-fusiegemeenten-2025.graph
  config/migrations/2024/2024-10/20241022085314-fusiegemeenten-2025/20241022085314-fusiegemeenten-2025.ttl
  config/migrations/2024/2024-10/20241022085314-fusiegemeenten-2025/20241022085315-move-fusiegemeenten.sparql
  config/migrations/2024/2024-10/20241022085314-fusiegemeenten-2025/20241022085316-fusiegemeenten-mock-users.sparql
  config/migrations/2024/2024-10/20241022085314-fusiegemeenten-2025/20241022093415-clear-tmp.sparql
  config/migrations/2024/2024-10/20241022100514-bestuursorganen-2025/20241022100514-bestuursorganen-gemeentes-2025.graph
  config/migrations/2024/2024-10/20241022100514-bestuursorganen-2025/20241022100514-bestuursorganen-gemeentes-2025.ttl
  config/migrations/2024/2024-10/20241022100514-bestuursorganen-2025/20241022100755-bestuursorganen-ocmw-2025.graph
  config/migrations/2024/2024-10/20241022100514-bestuursorganen-2025/20241022100755-bestuursorganen-ocmw-2025.ttl
  config/migrations/2024/2024-10/20241022100514-bestuursorganen-2025/20241022100922-bestuursorganen-provincies-2025.graph
  config/migrations/2024/2024-10/20241022100514-bestuursorganen-2025/20241022100922-bestuursorganen-provincies-2025.ttl
  config/migrations/2024/2024-10/20241022110253-set-up-bestuursperiodes/20241022110253-bestuursperiodes.graph
  config/migrations/2024/2024-10/20241022110253-set-up-bestuursperiodes/20241022110253-bestuursperiodes.ttl
  config/migrations/2024/2024-10/20241022110253-set-up-bestuursperiodes/20241022110254-link-bestuursperiodes.sparql
  config/migrations/2024/2024-10/20241022110253-set-up-bestuursperiodes/20241022110255-link-bestuursperiode-borsbeek.sparql
  config/migrations/2024/2024-10/20241022110253-set-up-bestuursperiodes/20241022110257-link-bestuursperiode-overige.sparql
  config/migrations/2024/2024-10/20241022111213-correct-start-date-fusies-2025.sparql
  config/migrations/2024/2024-10/20241023112651-kieslijsten/20241023112651-kieslijsten-districten.graph
  config/migrations/2024/2024-10/20241023112651-kieslijsten/20241023112651-kieslijsten-districten.ttl
  config/migrations/2024/2024-10/20241023112651-kieslijsten/20241023112652-kieslijsten-gemeentes.graph
  config/migrations/2024/2024-10/20241023112651-kieslijsten/20241023112652-kieslijsten-gemeentes.ttl
  config/migrations/2024/2024-10/20241023112651-kieslijsten/20241023112653-kieslijsten-provincies.graph
  config/migrations/2024/2024-10/20241023112651-kieslijsten/20241023112653-kieslijsten-provincies.ttl
  config/migrations/2024/2024-10/20241023112651-kieslijsten/20241023113601-kieslijst-personen.graph
  config/migrations/2024/2024-10/20241023112651-kieslijsten/20241023113601-kieslijst-personen.ttl
  config/resources/domain.lisp
  config/resources/repository.lisp
Labels: enhancement

#206 LMB LDES integration: keep track of 'last-update' timestamps for each administrative unit
  .changeset/lemon-rockets-occur.md
  config/ldes-client/processPage.ts
Labels: enhancement

#205 data(migrations): re-initialize mock accounts for districten and fusiegemeenten 2025
  .changeset/hip-schools-itch.md
  config/migrations/2024/2024-10/20241025073955-update-mock-accounts-districts.sparql
  config/migrations/2024/2024-10/20241025122025-update-mock-accounts-fusiegemeenten-2025.sparql
Labels: bug

#203 Feat/expose sparql endpoint
  .changeset/lemon-rockets-occur.md
  .changeset/perfect-readers-march.md
  config/dispatcher/dispatcher.ex
  config/ldes-client/processPage.ts
  docker-compose.yml
Labels: enhancement

#208 ldes-client: move `FIRST_PAGE` and `LDES_BASE` env vars to override.example file
  docker-compose.override.example.yml
  docker-compose.yml
Labels: internal
